'use strict';
const path=require('node:path'),fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto,createHash}=require('node:crypto');
const root=path.resolve(__dirname,'..');
const {DOM}=require(root+'/tests/dom-harness.js');
const report={suite:'continuity-signing-workflow-contract-v1.2',checks:[],scope:'Source-level DOM/native callback/export contract. No native signing, rendering, phone install, or external AI execution is established by these checks.'};
const hash=b=>createHash('sha256').update(b).digest('hex');
function load(native=true){
 const document=DOM(root+'/src/ui.html');document.addEventListener=()=>{};
 const c={console,Blob,File,Response,TextEncoder,TextDecoder,Uint8Array,Uint16Array,Uint32Array,DataView,ArrayBuffer,Map,Set,DecompressionStream,crypto:webcrypto,structuredClone,atob,btoa,URL,document,addEventListener(){},setTimeout:(fn,ms)=>{const x=setTimeout(fn,ms);if(ms>1000)x.unref();return x},clearTimeout,confirm:()=>true};c.globalThis=c;c.window=c;
 vm.createContext(c);for(const match of fs.readFileSync(root+'/dist/Workbench_Continuity_v1.2.0_PUBLIC.html','utf8').matchAll(/<script>\n([\s\S]*?)\n<\/script>/g)){if(!match[1].includes('let workspace = null;'))vm.runInContext(match[1],c);}
 const chunks=[],saves=[];let opens=0;
 if(native)c.WorkbenchNative={openLocalSigning(){opens++;return true},exportBegin(name,mime){chunks.length=0;this.name=name;return true},exportChunk(b){chunks.push(Buffer.from(b,'base64'));return true},exportFinish(){saves.push(Buffer.concat(chunks));queueMicrotask(()=>c.nativeExportResult(true,'Saved'));return true}};
 vm.runInContext(fs.readFileSync(root+'/src/continuity-ui.js','utf8'),c,{filename:'continuity-ui.js'});
 return{c,E:c.ContinuityEngine,C:c.ContinuityCarriers,UI:c.ContinuityUI,el:id=>document.getElementById(id),opens:()=>opens,saves};
}
async function check(name,fn){try{await fn();report.checks.push({name,status:'passed'});console.log('PASS '+name)}catch(e){report.checks.push({name,status:'failed',error:e.stack});console.error(e);process.exitCode=1}}
function receipt(){const apk={packageName:'dev.wakka.sample',versionName:'2.0',versionCode:2,minSdkVersion:26,splitName:null,size:22,sha256:'a'.repeat(64),verified:true,certificateSha256:['b'.repeat(64)],schemes:{v1:true,v2:true,v3:true,v31:false},verificationErrors:[],keystore:'NEVER_EXPORT_KEY_PATH',alias:'NEVER_EXPORT_ALIAS',password:'NEVER_EXPORT_PASSWORD'};return{format:'workbench-local-signing/1',status:'signed-and-verified',input:{...apk,verified:false},output:apk,reference:{...apk,versionCode:1},updateCompatible:true,updateStatus:'compatible',updateReasons:[],savedOnDevice:true,installObserved:true,autoReferenceSource:'installed package',privateKey:'NEVER_EXPORT_PRIVATE_MATERIAL'};}
(async()=>{
 const h=load();await h.UI.ready;
 await check('Signer is accessible before a project is open and opens native private workflow',async()=>{assert(h.el('sign-returned-top'));assert(h.el('sign-returned'));await h.UI.openLocalSigning();assert.equal(h.opens(),1);assert.equal(h.UI.getWorkspace(),null)});
 await check('Desktop HTML states actual Android signer is required',async()=>{const d=load(false);await d.UI.ready;assert.equal(await d.UI.openLocalSigning(),false);assert(d.el('live-status').textContent.includes('Android'));assert(d.el('content').innerHTML.includes('Android'))});
 await check('Open project exports explicit private-signing handoff without identity claims',async()=>{await h.UI.importBytes(new Uint8Array(fs.readFileSync(root+'/example/PocketNote.zip')),'CAPSULE_RESULT.zip',true);const out=await h.UI.exportPacket('private');const contract=JSON.parse(new TextDecoder().decode(out.files.get('SIGNING_HANDOFF.json')));assert.equal(contract.format,'continuity-private-signing-handoff/1');assert(contract.ai_build.version_code.includes('increase'));assert(contract.owner_finalization.update_claim.includes('checked reference'));assert(contract.credentials.includes('outside'));assert.equal(out.manifest['SIGNING_HANDOFF.json'].sha256,hash(out.files.get('SIGNING_HANDOFF.json')))});
 await check('Public receipt is attached as new evidence without altering source or owner runtime observations',async()=>{const before=[...h.UI.getWorkspace().files].map(([p,b])=>[p,hash(b)]),state=JSON.stringify(h.UI.getState());const result=await h.c.nativeSigningResult(true,JSON.stringify(receipt()));assert.equal(result.installObserved,false);assert.equal(result.savedOnDevice,true);assert.equal(JSON.stringify(h.UI.getState()),state);assert.deepEqual([...h.UI.getWorkspace().files].map(([p,b])=>[p,hash(b)]),before);const record=h.E.fileRecords(h.UI.getWorkspace()).find(x=>x.path.startsWith('evidence/local-signing/'));assert(record);const body=await record.blob.text();for(const secret of ['NEVER_EXPORT_KEY_PATH','NEVER_EXPORT_ALIAS','NEVER_EXPORT_PASSWORD','NEVER_EXPORT_PRIVATE_MATERIAL'])assert(!body.includes(secret));assert(body.includes('"updateCompatible": true'));const out=await h.UI.exportPacket('private');assert(out.files.has(record.path));assert(out.manifest[record.path])});
 await check('Same versionCode replacement is accepted while downgrade and mismatched identity claims are rejected',async()=>{const same=receipt();same.reference.versionCode=same.output.versionCode;assert.equal(h.UI.publicSigningReceipt(same).updateCompatible,true);const downgrade=receipt();downgrade.reference.versionCode=3;assert.throws(()=>h.UI.publicSigningReceipt(downgrade),/same or higher/);const otherKey=receipt();otherKey.reference.certificateSha256=['c'.repeat(64)];assert.throws(()=>h.UI.publicSigningReceipt(otherKey),/matching certificate/);const otherPackage=receipt();otherPackage.reference.packageName='dev.wakka.other';assert.throws(()=>h.UI.publicSigningReceipt(otherPackage),/matching certificate/);const conflicting=receipt();conflicting.updateStatus='no-reference';assert.throws(()=>h.UI.publicSigningReceipt(conflicting),/conflicting update claims/)});
 await check('Cancelled or invalid native receipt makes no evidence or success claim',async()=>{const before=h.E.fileRecords(h.UI.getWorkspace()).length;assert.equal(await h.c.nativeSigningResult(false,'Owner cancelled local signing'),false);assert.equal(h.E.fileRecords(h.UI.getWorkspace()).length,before);assert.equal(await h.c.nativeSigningResult(true,'{"format":"unknown"}'),false);assert.equal(h.E.fileRecords(h.UI.getWorkspace()).length,before)});
 await check('Public edition keeps both destinations available and explains first-time runtime setup',async()=>{assert(h.el('load-runtime'));assert(h.el('download-setup'));assert(h.el('target-destination'));assert(h.el('content').innerHTML.includes('Claude'));assert(h.el('content').innerHTML.includes('Grok'));assert.equal(h.C.inventory('claude').length,0);await assert.rejects(h.C.prepare(h.UI.getWorkspace(),{destination:'claude'}),/Load your build runtime/);});
 report.passed=report.checks.every(x=>x.status==='passed');report.finishedAt=new Date().toISOString();const reportPath=path.join(root,'evidence/signing-contract-results.json');fs.mkdirSync(path.dirname(reportPath),{recursive:true});report.sourceSha256=Object.fromEntries(['src/continuity-ui.js','src/continuity-carriers.js','src/ui.html','tools/prepare_build_template.py'].map(name=>[name,hash(fs.readFileSync(path.join(root,name)))]));report.testSha256=hash(fs.readFileSync(__filename));fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');
})();
